<a href="https://colab.research.google.com/github/TemsyToto/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/DSPT9_TemsyChen__LS_DS_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [ ]:
##### Begin Working Here #####

#I'll import the file and set my display to be able to view 100 rows and columns
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/Ames%20Housing%20Data/train.csv')
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,Wood,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,Typ,0,NaN,Attchd,1993.0,Unf,2,480,TA,TA,Y,40,30,0,320,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,CompShg,VinylSd,VinylSd,Stone,186.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2004.0,RFn,2,636,TA,TA,Y,255,57,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,CompShg,HdBoard,HdBoard,Stone,240.0,TA,TA,CBlock,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,Typ,2,TA,Attchd,1973.0,RFn,2,484,TA,TA,Y,235,204,228,0,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Artery,Norm,1Fam,1.5Fin,7,5,1931,1950,Gable,CompShg,BrkFace,Wd Shng,None,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0,Unf,0,952,952,GasA,Gd,Y,FuseF,1022,752,0,1774,0,0,2,0,2,2,TA,8,Min1,2,TA,Detchd,1931.0,Unf,2,468,Fa,TA,Y,90,0,205,0,0,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,BrkSide,Artery,Artery,2fmCon,1.5Unf,5,6,1939,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,BrkTil,TA,TA,No,GLQ,851,Unf,0,140,991,GasA,Ex,Y,SBrkr,1077,0,0,1077,1,0,1,0,2,2,TA,5,Typ,2,TA,Attchd,1939.0,RFn,1,205,Gd,TA,Y,0,4,0,0,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [ ]:
#Looking at specific columns

df['YearBuilt'].head()

0    2003
1    1976
2    2001
3    1915
4    2000
Name: YearBuilt, dtype: int64

In [ ]:
#Looking at the LotFrontage column
#Even though the numeric values are all integers, there are some NaN's
#so python converts all the values into floats.

df['LotFrontage'].head(15)

0     65.0
1     80.0
2     68.0
3     60.0
4     84.0
5     85.0
6     75.0
7      NaN
8     51.0
9     50.0
10    70.0
11    85.0
12     NaN
13    91.0
14     NaN
Name: LotFrontage, dtype: float64

In [ ]:
#Checking how many NaN's there are in the LotFrontage column
#There are 259 NaN's, more than any other value.

df['LotFrontage'].value_counts(dropna=False)

NaN      259
60.0     143
70.0      70
80.0      69
50.0      57
        ...
106.0      1
38.0       1
138.0      1
140.0      1
137.0      1
Name: LotFrontage, Length: 111, dtype: int64

In [ ]:
#Check what kind of datatype a NaN is

import numpy as np

type(np.NaN)

float

In [ ]:
#Make a smaller dataset of the following columns: 
# TotalBsmtSF
# 1stFlrSF
# 2ndFlrSF
# SalePrice

small_df = df[['TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'SalePrice']]
small_df

      TotalBsmtSF  1stFlrSF  2ndFlrSF  SalePrice
0             856       856       854     208500
1            1262      1262         0     181500
2             920       920       866     223500
3             756       961       756     140000
4            1145      1145      1053     250000
...           ...       ...       ...        ...
1455          953       953       694     175000
1456         1542      2073         0     210000
1457         1152      1188      1152     266500
1458         1078      1078         0     142125
1459         1256      1256         0     147500

[1460 rows x 4 columns]

In [ ]:
#Add up all the square footage to create a new column TotalSqFtg

df['TotalSqFtg'] = df['TotalBsmtSF'] + df['1stFlrSF'] + df['2ndFlrSF']
df['TotalSqFtg']

0       2566
1       2524
2       2706
3       2473
4       3343
        ...
1455    2600
1456    3615
1457    3492
1458    2156
1459    2512
Name: TotalSqFtg, Length: 1460, dtype: int64

In [ ]:
#Make another column PricePerSqFtg

df['PricePerSqFtg'] = df['SalePrice']/df['TotalSqFtg']
df['PricePerSqFtg']

0       81.254871
1       71.909667
2       82.594235
3       56.611403
4       74.783129
          ...
1455    67.307692
1456    58.091286
1457    76.317297
1458    65.920686
1459    58.718153
Name: PricePerSqFtg, Length: 1460, dtype: float64

In [ ]:
#Check if the new columns were added to the dataset

df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,TotalSqFtg,PricePerSqFtg
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,2566,81.254871
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,2524,71.909667
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,2706,82.594235
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,2473,56.611403
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,3343,74.783129

In [ ]:
#Work on the lending club data
#Download the data set with the !wget shell command

!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-09-05 17:35:21--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 35.161.89.82, 54.148.13.215, 54.244.115.45
Connecting to resources.lendingclub.com (resources.lendingclub.com)|35.161.89.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.1’

LoanStats_2018Q4.cs     [               <=>  ]  22.28M  6.15MB/s    in 3.7s

2020-09-05 17:35:26 (5.96 MB/s) - ‘LoanStats_2018Q4.csv.zip.1’ saved [23360898]

In [ ]:
#Unzip the file with the shell command

!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [ ]:
#Looks at the head and tail using shell commands

!head LoanStats_2018Q4.csv
!tail LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","27975","27975","27975"," 36 months"," 14.47%","962.52","C","C2","Conductor ","10+ years","MORTGAGE","180000","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","117xx","NY","11.47","0","Jul-1995","0","39","","10","0","29711","66.8%","19","w","0.00","0.00","31804.5298492634","31804.53","27975.00","3829.53","0.0","0.0","0.0","Jan-2020","20288.02","","Mar-2020","0","","1","Individual","","","","0","0","206072","0","1","0","1","17","15676","63","0","1","10861","65","44500","1","4","2","2","20607","7416","74.9","0","0","17","281","20","17","5","20","39","1","39","0","5","7","5","6","1","8","13","7","10","0","0","0","0","78.9","60","0","0","286525","45387","29500","25025","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 60 months"," 12.98%","227.43","B","B5","Printer","9 years","RENT","60000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","660xx","KS","14.9","0","May-2007","0","","112","7","1","10677","54.2%","12","w","7352.95","7352.95","4487.31","4487.31","2647.05","1840.26","0.0","0.0","0.0","Aug-2020","227.43","Sep-2020","Aug-2020","0","","1","Individual","","","","0","469","27595","0","2","1","1","11","16918","103","0","1","4337","76","19700","5","0","7","2","3942","4278","67.1","0","0","139","74","20","11","0","20","","0","","0","3","5","3","4","6","5","6","5","7","0","0","0","1","100","33.3","1","0","36200","27595","13000","16500","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","28000","28000","28000"," 60 months"," 13.56%","645.15","C","C1","Project Manager","10+ years","MORTGAGE","128500","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","760xx","TX","27.35","1","Jul-1987","0","24","","16","0","55206","75%","31","w","20667.91","20667.91","12871.36","12871.36","7332.09","5539.27","0.0","0.0","0.0","Aug-2020","645.15","Sep-2020","Aug-2020","0","71","1","Individual","","","","0","0","455106","1","2","1","1","2","47753","79","0","0","17372","75","73700","0","1","1","1","30340","6875","98","0","0","126","373","72","2","3","72","65","3","24","0","9","11","10","10","9","11","17","11","15","","0","0","1","94","100","0","0","542027","128345","55000","60331","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","16000","16000","16000"," 60 months"," 13.56%","368.66","C","C1","LMSW","10+ years","RENT","46000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","787xx","TX","11.09","1","Oct-1997","1","11","","9","0","18946","32.1%","21","w","11503.84","11503.84","7570.88","7570.88","4496.16","3074.72","0.0","0.0","0.0","Aug-2020","368.66","Sep-2020","Aug-2020","0","","1","Individual","","","","0","0","128218","1","2","0","0","37","109272","101","1","1","14999","36","59000","0","1","1","1","16027","38663","32.9","0","0","133","254","5","5","0","42","","5","","0","2","3","5","8","10","7","11","3","9","0","0","0","1","94.7","20","0","0","138125","128218","57600","79125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","7500","7500","7500"," 36 months"," 10.72%","244.55","B","B2","Program Manager","2 years","RENT","84000","Not Verified","Dec-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","600xx","IL","3.86","0","May-2005","1","","114","9","1","2200","12.6%","17","w","0.00","0.00","2829.93","2829.93","1465.61","484.09","0.0","880.23","158.4414","Sep-2019","244.55","","Mar-2020","0","","1","Individual","","","","0","0","381442","1","5","2","2","3","18633","111","0","2","2123","61","17400","3","1","3","5","42382","15200","12.6","0","0","163","105","13","3","1","13","","3","","0","2","2","3","4","10","3","6","2","9","0","0","0","2","76.5","0","1","0","403892","20833","17400","16812","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","3500","3500","3500"," 36 months"," 20.89%","131.67","D","D4","gas attendant","10+ years","MORTGAGE","40000","Source Verified","Dec-2018","Current","n","","","car","Car financing","078xx","NJ","9.09","0","Oct-2004","1","24","","4","0","1944","33.5%","18","w","1955.78","1955.78","2495.64","2495.64","1544.22","951.42","0.0","0.0","0.0","Aug-2020","131.67","Sep-2020","Aug-2020","0","48","1","Joint App","59500","10.59","Source Verified","0","0","189794","1","1","1","1","7","24958","100","2","2","1317","87","5800","1","0","3","3","47449","3683","26.3","0","0","150","170","1","1","4","8","48","1","48","2","1","2","1","8","3","2","11","2","4","0","0","0","3","38.9","0","0","0","217000","26902","5000","25000","6902","May-2003","0","3","6","47.9","0","21","0","0","46","N","","","","","","","","","","","","","","","N","","","","","",""
"","","16000","16000","16000"," 60 months"," 26.31%","481.99","E","E4","Financial Relationship Associate","< 1 year","RENT","33000","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","290xx","SC","33.62","0","Sep-2010","1","","","17","0","22872","65.5%","22","w","12749.04","12749.04","9604.72","9604.72","3250.96","6353.76","0.0","0.0","0.0","Aug-2020","481.99","Sep-2020","Aug-2020","0","","1","Individual","","","","0","0","29869","1","1","0","1","24","6997","65","1","1","2703","65","34900","0","3","1","2","1757","4596","66.9","0","0","29","99","2","2","0","2","","3","","0","6","11","9","13","2","16","20","11","17","0","0","0","1","100","55.6","0","0","45709","29869","13900","10809","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","13000","13000","13000"," 36 months"," 23.40%","505.95","E","E1","Sale Representative","2 years","MORTGAGE","90000","Verified","Dec-2018","Current","n","","","other","Other","191xx","PA","39.73","0","May-2007","0","","","14","0","52013","83.1%","20","w","8968.74","8968.74","8069.85","8069.85","4031.26","4038.59","0.0","0.0","0.0","Aug-2020","505.95","Sep-2020","Aug-2020","0","","1","Individual","","","","0","0","87876","1","7","1","3","1","35863","48","0","1","18037","64","62600","2","0","1","4","6277","9503","83.8","0","0","131","139","16","1","0","16","","10","","0","6","7","6","7","11","7","9","7","14","0","0","0","1","100","66.7","0","0","137276","87876","58600","74676","","","","","","","","","","","","N","CVD19SKIP","INCOME_CURTAILMENT","COMPLETE","4","0","May-2020","Jul-2020","May-2020","4","0","ACTIVE","1086.68","9481.75","55.8","N","","","","","",""
"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","2449.86","2449.86","4174.07","4174.07","3150.14","1023.93","0.0","0.0","0.0","Aug-2020","190.21","Sep-2020","Aug-2020","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","4427.45","4427.45","7620.38","7620.38","5572.55","2047.83","0.0","0.0","0.0","Aug-2020","346.76","Sep-2020","Aug-2020","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","2187.38","2187.38","3732.49","3732.49","2812.62","919.87","0.0","0.0","0.0","Aug-2020","169.83","Sep-2020","Aug-2020","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","4285.08","4177.96","7193.6","7013.76","5714.92","1478.68","0.0","0.0","0.0","Aug-2020","327.68","Sep-2020","Aug-2020","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","4495.59","4495.59","7824.37","7824.37","5504.41","2319.96","0.0","0.0","0.0","Aug-2020","356.08","Sep-2020","Aug-2020","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [ ]:
#Put it into a table
#There are columns and rows of NaN's, and spaces between columns


df = pd.read_csv('LoanStats_2018Q4.csv')
df.head(50)
df.tail(50)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,113,114,115,116,117,118,119,120,121,126,127,131,132,134,135,136,141,142,143) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
NaN                                              NaN 25000 25000 24975  36 months  27.27% 1024.26 E   E5  NaN                                   < 1 year  MORTGAGE 122000.0 Not Verified    Oct-2018 Charged Off n   NaN NaN small_business     Business                705xx LA  39.78 0   Aug-1999 4   NaN   NaN   13  0   34805   54.1% 38  f   0.0      0.0      14301.76           14287.46 7420.52  6881.24  0.0  0.0     0.0      Dec-2019 1024.26  NaN      Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      330681.0 0   3   0   2   19.0  83228.0  56.0  2   2   16864   59.0 64300   8   2   8   4   25437.0 28384.0 54.8  0   0   229.0 179 8   8   5   9.0   NaN   1.0  NaN   0   6   7   7   11  17  8   15  7   13  0.0 0   0   2   100.0 28.6  0   0   442036.0 140505.0 62800   126224.0 NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     35000 35000 35000  36 months  13.56% 1188.76 C   C1  Disability Employee Program Manager   10+ years MORTGAGE 100000.0 Source Verified Oct-2018 Fully Paid  n   NaN NaN debt_consolidation Debt consolidation      277xx NC  14.8  0   Nov-1998 0   NaN   67.0  11  1   16283   30.5% 26  f   0.0      0.0      35703.231624039305 35703.23 35000.0  703.23   0.0  0.0     0.0      Nov-2018 35769.15 NaN      May-2020 0   NaN   1   Individual NaN      NaN   NaN             0   57     223512.0 2   2   2   3   3.0   32414    70.0  1   2   7602    49.0 53300   3   0   4   6   22351.0 32017.0 33.7  0   0   200.0 238 10  3   2   10.0  NaN   3.0  NaN   0   4   4   6   12  10  8   14  4   10  0.0 0   0   4   100.0 0.0   1   0   275438.0 48697    48300   46620    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     15500 15500 15500  36 months   8.46% 489.01  A   A5  Compliance Consultant                 3 years   MORTGAGE 121000.0 Source Verified Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      302xx GA  24.63 0   Apr-1987 0   NaN   NaN   18  0   66568.0 63%   26  f   0.0      0.0      17266.37           17266.37 15500.0  1766.37  0.0  0.0     0.0      Aug-2020 7015.37  Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      511885.0 1   1   0   0   39.0  15582.0  45.0  0   1   21924.0 58.0 105700  0   2   3   2   28438   7232.0  89.8  0   0   136.0 377 24  2   4   71.0  NaN   6.0  NaN   0   4   9   4   6   5   14  17  9   18  0.0 0   0   1   100.0 100.0 0   0   597065.0 82150.0  70600   35000    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     9500  9500  9500   36 months  14.47% 326.87  C   C2  Technical Services Manager            10+ years MORTGAGE 70000.0  Source Verified Oct-2018 Current     n   NaN NaN vacation           Vacation                600xx IL  15.68 0   Jun-2005 0   56.0  NaN   5   0   10389   16%   13  f   4187.26  4187.26  7172.05            7172.05  5312.74  1859.31  0.0  0.0     0.0      Aug-2020 326.87   Sep-2020 Aug-2020 0   56.0  1   Individual NaN      NaN   NaN             0   0      32667.0  0   2   1   1   7.0   22278    64.0  0   0   6058    33.0 65000   1   0   2   1   6533.0  54611.0 16.0  0   0   37.0  159 47  7   4   47.0  NaN   7.0  56.0  1   3   3   3   6   2   3   7   3   5   0.0 0   0   1   92.3  0.0   0   0   100089.0 32667    65000   35089.0  NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     35000 35000 35000  60 months  17.97% 888.2   D   D1  District Manager                      2 years   RENT     94000.0  Not Verified    Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      940xx CA  30.92 1   Jan-2010 0   22.0  NaN   8   0   17729   36.3% 14  w   25595.76 25595.76 19453.05           19453.05 9404.24  10048.81 0.0  0.0     0.0      Aug-2020 888.2    Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      78347.0  0   3   1   2   11.0  60618.0  77.0  0   1   7669    51.0 48900   1   0   0   5   9793.0  30171.0 37.0  0   0   69.0  104 23  11  0   27.0  NaN   14.0 NaN   0   3   3   3   5   5   4   7   3   8   0.0 0   0   1   92.9  0.0   0   0   140757.0 78347.0  47900   87397.0  NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     8000  8000  8000   36 months  14.47% 275.26  C   C2  NaN                                   NaN       MORTGAGE 42588.0  Not Verified    Oct-2018 Current     n   NaN NaN credit_card        Credit card refinancing 212xx MD  35.47 0   Jan-1999 0   NaN   NaN   12  0   33197.0 85.8% 15  w   3526.09  3526.09  6039.64            6039.64  4473.91  1565.73  0.0  0.0     0.0      Aug-2020 275.26   Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      78561.0  0   4   0   1   24.0  9777     40.0  0   0   2396    68.0 38700   0   0   1   1   6547.0  0.0     100.0 0   0   57.0  149 29  24  1   29.0  NaN   4.0  NaN   0   5   7   5   5   6   7   8   7   12  0.0 0   0   0   100.0 100.0 0   0   129102.0 42974    7700    24758    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     40000 40000 40000  60 months   7.84% 808.0   A   A4  Budget Analyst                        10+ years MORTGAGE 85800.0  Source Verified Oct-2018 Fully Paid  n   NaN NaN debt_consolidation Debt consolidation      840xx UT  10.95 0   Sep-1995 0   NaN   NaN   27  0   16476   11.4% 64  w   0.0      0.0      44797.11           44797.11 40000.0  4797.11  0.0  0.0     0.0      Jul-2020 28680.67 NaN      Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      395990.0 6   1   3   5   4.0   23998    96.0  6   8   16086.0 24.0 144400  2   9   2   14  15840.0 95714.0 14.4  0   0   158.0 276 2   2   7   4.0   NaN   7.0  NaN   0   1   2   13  19  17  24  40  2   27  0.0 0   0   9   100.0 8.3   0   0   545400.0 40474    111800  25000    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     12800 12800 12800  36 months   8.46% 403.83  A   A5  Packer                                10+ years OWN      30000.0  Source Verified Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      305xx GA  29.21 0   May-1997 1   59.0  NaN   5   0   0       0%    10  w   5365.49  5365.49  8897.83            8897.83  7434.51  1463.32  0.0  0.0     0.0      Aug-2020 403.83   Sep-2020 Aug-2020 0   59.0  1   Individual NaN      NaN   NaN             0   0      8216     0   2   0   2   13.0  8216.0   78.0  0   0   0       37.0 11500   2   0   1   2   1643.0  NaN     NaN   0   0   15.0  256 55  13  1   NaN   59.0  0.0  59.0  1   0   0   0   4   2   3   7   0   5   0.0 0   0   0   90.0  NaN   0   0   21996.0  8216     0       10496.0  NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     5500  5500  5500   36 months   7.84% 171.95  A   A4  Driver                                10+ years RENT     42000.0  Not Verified    Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      070xx NJ  19.91 0   Feb-1997 1   NaN   NaN   13  0   3084    7.5%  28  w   2293.13  2293.13  3794.88            3794.88  3206.87  588.01   0.0  0.0     0.0      Aug-2020 171.95   Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      52333.0  1   3   0   2   16.0  49249    55.0  2   4   764     17.0 41000   1   0   2   6   4361.0  27781.0 6.8   0   0   97.0  259 6   6   0   18.0  NaN   0.0  NaN   0   3   7   4   6   9   10  19  7   13  0.0 0   0   2   100.0 0.0   0   0   85667.0  52333.0  29800   44667    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     40000 40000 39975  36 months   6.11% 1218.88 A   A1  Senior Lead Technologist              10+ years MORTGAGE 150000.0 Verified        Oct-2018 Current     n   NaN NaN credit_card        Credit card refinancing 201xx VA  25.36 0   Oct-1995 0   NaN   NaN   10  0   85552.0 76.8% 21  f   15293.63 15284.07 28013.88           27996.37 24706.37 3307.51  0.0  0.0     0.0      Aug-2020 1218.88  Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      500575.0 1   2   0   1   17.0  44453    77.0  1   2   38532.0 77.0 100200  0   0   0   3   50058.0 14648.0 76.8  0   0   275.0 173 6   6   4   6.0   NaN   17.0 NaN   0   7   7   7   8   8   7   9   7   10  0.0 0   0   1   100.0 71.4  0   0   573278.0 130005.0 100200  69024.0  NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     20275 20275 20275  60 months  22.35% 564.02  D   D5  manager                               9 years   MORTGAGE 65000.0  Source Verified Oct-2018 Fully Paid  n   NaN NaN debt_consolidation Debt consolidation      846xx UT  20.42 0   Jan-2009 1   39.0  84.0  16  1   14213   47.4% 32  w   0.0      0.0      23144.7088998793   23144.71 20275.0  2869.71  0.0  0.0     0.0      May-2019 19810.94 NaN      Jun-2019 0   NaN   1   Individual NaN      NaN   NaN             0   0      229591.0 3   5   2   3   5.0   36349.0  85.0  2   3   3847    69.0 30000   1   6   3   7   14349   9463.0  43.0  0   0   116.0 71  2   2   6   22.0  39.0  1.0  39.0  0   4   8   4   4   15  10  11  8   16  0.0 0   0   4   93.8  0.0   1   0   255375.0 50562    16600   42975    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     1500  1500  1500   36 months  11.55% 49.5    B   B4  House keeping                         6 years   MORTGAGE 62000.0  Not Verified    Oct-2018 Current     n   NaN NaN other              Other                   864xx AZ  11.36 0   Jun-2012 0   NaN   NaN   16  0   8398    14.1% 20  f   645.43   645.43   1088.04            1088.04  854.57   233.47   0.0  0.0     0.0      Aug-2020 49.5     Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      21663    2   2   1   2   1.0   13265    80.0  2   4   1580    28.0 59600   0   0   0   6   1354    39387.0 10.7  0   0   27.0  75  4   1   0   9.0   NaN   15.0 NaN   0   9   11  11  12  3   14  16  11  16  0.0 0   0   3   100.0 9.1   0   0   76200    21663    44100   16600    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     17500 17500 17500  36 months  13.56% 594.38  C   C1  NaN                                   < 1 year  MORTGAGE 150000.0 Not Verified    Oct-2018 Fully Paid  n   NaN NaN home_improvement   Home improvement        803xx CO  38.62 0   Aug-1991 0   NaN   NaN   14  0   54199   65.8% 21  w   0.0      0.0      20059.6132492859   20059.61 17500.0  2559.61  0.0  0.0     0.0      Feb-2020 54.13    NaN      Mar-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      671230.0 1   4   2   2   4.0   215207.0 24.0  0   0   29354.0 56.0 82400   0   1   1   2   47945.0 6672.0  88.9  0   0   263.0 325 35  4   1   40.0  NaN   10.0 NaN   0   6   7   6   7   10  9   10  7   14  0.0 0   0   2   100.0 50.0  0   0   838857.0 269406.0 60200   314780.0 NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     40000 40000 40000  60 months   6.67% 785.84  A   A2  Principal                             3 years   RENT     165000.0 Source Verified Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      941xx CA  16.2  0   Nov-2003 1   NaN   NaN   11  0   4266    4.3%  21  f   26851.78 26851.78 17370.01           17370.01 13148.22 4221.79  0.0  0.0     0.0      Aug-2020 785.84   Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   0      61122    2   4   3   3   3.0   56856    77.0  1   1   3178    35.0 98500   3   0   8   4   5557    90934.0 4.5   0   0   178.0 177 2   2   0   2.0   NaN   3.0  NaN   0   4   4   6   10  8   7   13  4   11  0.0 0   0   4   100.0 0.0   0   0   172695.0 61122    95200   74195    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     18000 18000 18000  60 months  27.27% 552.55  E   E5  Kennel Manager                        8 years   MORTGAGE 35000.0  Source Verified Oct-2018 Current     n   NaN NaN credit_card        Credit card refinancing 178xx PA  47.59 0   Mar-2005 0   NaN   62.0  12  1   7881    60.2% 28  w   14108.73 14108.73 12155.56           12155.56 3891.27  8264.29  0.0  0.0     0.0      Aug-2020 552.55   Sep-2020 Aug-2020 0   NaN   1   Joint App  70000.0  25.66 Source Verified 0   74     40785    2   3   1   2   10.0  32904    71.0  4   5   1638    69.0 13100   1   1   3   7   3399    1118.0  75.7  0   0   130.0 162 2   2   0   3.0   NaN   3.0  NaN   0   3   9   3   4   15  9   13  9   12  0.0 0   0   5   100.0 66.7  1   0   59199.0  40785    4600    46099    15037.0 Apr-2004 0.0 1.0 8.0  71.2 3.0 8.0  0.0 0.0 NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     35000 35000 35000  36 months  11.06% 1146.85 B   B3  Vice President/Mortgage Loan Officer  8 years   OWN      125000.0 Source Verified Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      730xx OK  26.01 0   Aug-2003 0   NaN   NaN   11  0   8817    66.3% 19  w   14998.52 14998.52 25348.98           25348.98 20001.48 5347.5   0.0  0.0     0.0      Aug-2020 1146.85  Sep-2020 Aug-2020 0   NaN   1   Individual NaN      NaN   NaN             0   50     99903.0  1   4   1   4   2.0   91086.0  83.0  1   4   2576    80.0 13300   0   0   2   8   9082    1648.0  82.1  0   0   64.0  46  11  2   1   16.0  NaN   2.0  NaN   0   4   5   4   4   10  7   8   5   11  0.0 0   0   2   100.0 75.0  0   0   123453.0 99903.0  9200    110153.0 NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN
                                                     15000 15000 15000  60 months  16.91% 372.07  C   C5  NaN                                   NaN       RENT     42000.0  Not Verified    Oct-2018 Charged Off n   NaN NaN debt_consolidation Debt consolidation      070xx NJ  18.71 0   Sep-1989 0   NaN   NaN   8   0   13967   29.3% 15  w   0.0      0.0      5670.68            5670.68  1712.78  1993.83  0.0  1964.07 353.5326 Aug-2019 372.07   NaN      Mar-2020 0   NaN   1   Individual NaN      NaN   NaN             0   58     24769    3   1   0   0   33.0  10802    60.0  4   5   5589    38.0 47700   0   0   0   5   3538    33733.0 29.3  0   0   33.0  348 4   4   0   4.0   NaN   17.0 NaN   0   4   4   6   12  1   7   14  4   8   0.0 0   0   4   100.0 0.0   0   0   65771    24769    47700   18071    NaN     NaN      NaN NaN NaN  NaN  NaN NaN  NaN NaN NaN  N   NaN        NaN                NaN      NaN NaN    NaN      NaN      NaN      NaN NaN NaN    NaN       NaN      NaN    N   NaN NaN NaN NaN NaN                                                NaN

In [ ]:
#Looking at the shape of the table
#It says there is only 1 column, that's a problem
#Clearly there is more than one column

print(df.shape)

(128415, 1)

In [ ]:
#Use the skiprows parameter to fix the table
#That fixed it, now there are 144 columns

df = pd.read_csv('LoanStats_2018Q4.csv', skiprows = 1)
df.shape
df.head()
df.tail()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,...,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
128409,NaN,NaN,5000.0,5000.0,5000.0,36 months,13.56%,169.83,C,C1,Payoff Clerk,10+ years,MORTGAGE,35360.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,381xx,TN,11.30,1.0,Jun-2006,0.0,21.0,NaN,9.0,0.0,2597.0,27.3%,15.0,f,2187.38,2187.38,3732.49,3732.49,2812.62,919.87,0.0,0.0,0.0,Aug-2020,169.83,Sep-2020,Aug-2020,0.0,...,6.0,6.0,7.0,3.0,9.0,0.0,0.0,0.0,3.0,92.9,50.0,0.0,0.0,93908.0,4976.0,3000.0,6028.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128410,NaN,NaN,10000.0,10000.0,9750.0,36 months,11.06%,327.68,B,B3,NaN,NaN,RENT,44400.0,Source Verified,Oct-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,980xx,WA,11.78,0.0,Oct-2008,2.0,40.0,NaN,15.0,0.0,6269.0,13.1%,25.0,f,4285.08,4177.96,7193.60,7013.76,5714.92,1478.68,0.0,0.0,0.0,Aug-2020,327.68,Sep-2020,Aug-2020,0.0,...,3.0,14.0,22.0,4.0,15.0,0.0,0.0,0.0,3.0,92.0,0.0,0.0,0.0,57871.0,16440.0,20500.0,10171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128411,NaN,NaN,10000.0,10000.0,10000.0,36 months,16.91%,356.08,C,C5,Key Accounts Manager,2 years,RENT,80000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,other,Other,021xx,MA,17.72,1.0,Sep-2006,0.0,14.0,NaN,17.0,0.0,1942.0,30.8%,31.0,w,4495.59,4495.59,7824.37,7824.37,5504.41,2319.96,0.0,0.0,0.0,Aug-2020,356.08,Sep-2020,Aug-2020,0.0,...,22.0,2.0,9.0,1.0,17.0,0.0,0.0,0.0,1.0,74.2,0.0,0.0,0.0,73669.0,59194.0,4000.0,67369.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128412,Total amount funded in policy code 1: 2050909275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128413,Total amount funded in policy code 2: 820109297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Check null values
pd.set_option('display.max_rows', 200)

df.isnull().sum()

id                                            128412
member_id                                     128414
loan_amnt                                          2
funded_amnt                                        2
funded_amnt_inv                                    2
term                                               2
int_rate                                           2
installment                                        2
grade                                              2
sub_grade                                          2
emp_title                                      20949
emp_length                                     11706
home_ownership                                     2
annual_inc                                         2
verification_status                                2
issue_d                                            2
loan_status                                        2
pymnt_plan                                         2
url                                           128414
desc                                          128414
purpose                                            2
title                                              2
zip_code                                           2
addr_state                                         2
dti                                              239
delinq_2yrs                                        2
earliest_cr_line                                   2
inq_last_6mths                                     2
mths_since_last_delinq                         72198
mths_since_last_record                        112964
open_acc                                           2
pub_rec                                            2
revol_bal                                          2
revol_util                                       158
total_acc                                          2
initial_list_status                                2
out_prncp                                          2
out_prncp_inv                                      2
total_pymnt                                        2
total_pymnt_inv                                    2
total_rec_prncp                                    2
total_rec_int                                      2
total_rec_late_fee                                 2
recoveries                                         2
collection_recovery_fee                            2
last_pymnt_d                                     161
last_pymnt_amnt                                    2
next_pymnt_d                                   46260
last_credit_pull_d                                 3
collections_12_mths_ex_med                         2
mths_since_last_major_derog                    99234
policy_code                                        2
application_type                                   2
annual_inc_joint                              111632
dti_joint                                     111632
verification_status_joint                     113566
acc_now_delinq                                     2
tot_coll_amt                                       2
tot_cur_bal                                        2
open_acc_6m                                        2
open_act_il                                        2
open_il_12m                                        2
open_il_24m                                        2
mths_since_rcnt_il                              4480
total_bal_il                                       2
il_util                                        20276
open_rv_12m                                        2
open_rv_24m                                        2
max_bal_bc                                         2
all_util                                          39
total_rev_hi_lim                                   2
inq_fi                                             2
total_cu_tl                                        2
inq_last_12m                                       2
acc_open_past_24mths                               2
avg_cur_bal                                       15
bc_open_to_buy                                  1693
bc_util                                         1756
chargeoff_within_12_mths                           2
delinq_amnt                                        2
mo_sin_old_il_acct                              4480
mo_sin_old_rev_tl_op                               2
mo_sin_rcnt_rev_tl_op                              2
mo_sin_rcnt_tl                                     2
mort_acc                                           2
mths_since_recent_bc                            1593
mths_since_recent_bc_dlq                      103245
mths_since_recent_inq                          16049
mths_since_recent_revol_delinq                 91632
num_accts_ever_120_pd                              2
num_actv_bc_tl                                     2
num_actv_rev_tl                                    2
num_bc_sats                                        2
num_bc_tl                                          2
num_il_tl                                          2
num_op_rev_tl                                      2
num_rev_accts                                      2
num_rev_tl_bal_gt_0                                2
num_sats                                           2
num_tl_120dpd_2m                                2861
num_tl_30dpd                                       2
num_tl_90g_dpd_24m                                 2
num_tl_op_past_12m                                 2
pct_tl_nvr_dlq                                     2
percent_bc_gt_75                                1694
pub_rec_bankruptcies                               2
tax_liens                                          2
tot_hi_cred_lim                                    2
total_bal_ex_mort                                  2
total_bc_limit                                     2
total_il_high_credit_limit                         2
revol_bal_joint                               111632
sec_app_earliest_cr_line                      111632
sec_app_inq_last_6mths                        111632
sec_app_mort_acc                              111632
sec_app_open_acc                              111632
sec_app_revol_util                            111890
sec_app_open_act_il                           111632
sec_app_num_rev_accts                         111632
sec_app_chargeoff_within_12_mths              111632
sec_app_collections_12_mths_ex_med            111632
sec_app_mths_since_last_major_derog           123260
hardship_flag                                   4788
hardship_type                                 115292
hardship_reason                               115279
hardship_status                               115278
deferral_term                                 115278
hardship_amount                               110491
hardship_start_date                           115278
hardship_end_date                             115278
payment_plan_start_date                       115291
hardship_length                               115278
hardship_dpd                                  115279
hardship_loan_status                          117396
orig_projected_additional_accrued_interest    110501
hardship_payoff_balance_amount                110491
hardship_last_payment_amount                  110491
debt_settlement_flag                               2
debt_settlement_flag_date                     127477
settlement_status                             127477
settlement_date                               127477
settlement_amount                             127477
settlement_percentage                         127477
settlement_term                               127477
dtype: int64

In [ ]:
#Skip the 2 lines of footer

df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1, skipfooter=2)
df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,...,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,27975,27975,27975.0,36 months,14.47%,962.52,C,C2,Conductor,10+ years,MORTGAGE,180000.0,Not Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,117xx,NY,11.47,0,Jul-1995,0,39.0,NaN,10,0,29711,66.8%,19,w,0.00,0.00,31804.529849,31804.53,27975.00,3829.53,0.0,0.00,0.0000,Jan-2020,20288.02,NaN,Mar-2020,0,...,1,8,13,7,10,0.0,0,0,0,78.9,60.0,0,0,286525,45387,29500,25025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,10000,10000,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7352.95,7352.95,4487.310000,4487.31,2647.05,1840.26,0.0,0.00,0.0000,Aug-2020,227.43,Sep-2020,Aug-2020,0,...,6,5,6,5,7,0.0,0,0,1,100.0,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,28000,28000,28000.0,60 months,13.56%,645.15,C,C1,Project Manager,10+ years,MORTGAGE,128500.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,760xx,TX,27.35,1,Jul-1987,0,24.0,NaN,16,0,55206,75%,31,w,20667.91,20667.91,12871.360000,12871.36,7332.09,5539.27,0.0,0.00,0.0000,Aug-2020,645.15,Sep-2020,Aug-2020,0,...,9,11,17,11,15,NaN,0,0,1,94.0,100.0,0,0,542027,128345,55000,60331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,16000,16000,16000.0,60 months,13.56%,368.66,C,C1,LMSW,10+ years,RENT,46000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,787xx,TX,11.09,1,Oct-1997,1,11.0,NaN,9,0,18946,32.1%,21,w,11503.84,11503.84,7570.880000,7570.88,4496.16,3074.72,0.0,0.00,0.0000,Aug-2020,368.66,Sep-2020,Aug-2020,0,...,10,7,11,3,9,0.0,0,0,1,94.7,20.0,0,0,138125,128218,57600,79125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,7500,7500,7500.0,36 months,10.72%,244.55,B,B2,Program Manager,2 years,RENT,84000.0,Not Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,600xx,IL,3.86,0,May-2005,1,NaN,114.0,9,1,2200,12.6%,17,w,0.00,0.00,2829.930000,2829.93,1465.61,484.09,0.0,880.23,158.4414,Sep-2019,244.55,NaN,Mar-2020,0,...,10,3,6,2,9,0.0,0,0,2,76.5,0.0,1,0,403892,20833,17400,16812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128407,NaN,NaN,23000,23000,23000.0,36 months,15.02%,797.53,C,C3,Tax Consultant,10+ years,MORTGAGE,75000.0,Source Verified,Oct-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,352xx,AL,20.95,1,Aug-1985,2,22.0,NaN,12,0,22465,43.6%,28,w,0.00,0.00,1547.080000,1547.08,1025.67,521.41,0.0,0.00,0.0000,Dec-2018,797.53,NaN,Nov-2018,0,...,3,9,19,5,12,0.0,0,0,7,96.4,14.3,0,0,296500,40614,47100,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128408,NaN,NaN,10000,10000,10000.0,36 months,15.02%,346.76,C,C3,security guard,5 years,MORTGAGE,38000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,443xx,OH,13.16,3,Jul-1982,0,6.0,NaN,11,0,5634,37.1%,16,w,4427.45,4427.45,7620.380000,7620.38,5572.55,2047.83,0.0,0.00,0.0000,Aug-2020,346.76,Sep-2020,Aug-2020,0,...,1,8,11,5,11,0.0,0,0,1,73.3,40.0,0,0,91403,9323,9100,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128409,NaN,NaN,5000,5000,5000.0,36 months,13.56%,169.83,C,C1,Payoff Clerk,10+ years,MORTGAGE,35360.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,381xx,TN,11.30,1,Jun-2006,0,21.0,NaN,9,0,2597,27.3%,15,f,2187.38,2187.38,3732.490000,3732.49,2812.62,919.87,0.0,0.00,0.0000,Aug-2020,169.83,Sep-2020,Aug-2020,0,...,6,6,7,3,9,0.0,0,0,3,92.9,50.0,0,0,93908,4976,3000,6028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128410,NaN,NaN,10000,10000,9750.0,36 months,11.06%,327.68,B,B3,NaN,NaN,RENT,44400.0,Source Verified,Oct-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,980xx,WA,11.78,0,Oct-2008,2,40.0,NaN,15,0,6269,13.1%,25,f,4285.08,4177.96,7193.600000,7013.76,5714.92,1478.68,0.0,0.00,0.0000,Aug-2020,327.68,Sep-2020,Aug-2020,0,...,3,14,22,4,15,0.0,0,0,3,92.0,0.0,0,0,57871,16440,20500,10171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128411,NaN,NaN,10000,10000,10000.0,36 months,16.91%,356.08,C,C5,Key Accounts Manager,2 years,RENT,80000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,other,Other,021xx,MA,17.72,1,Sep-2006,0,14.0,NaN,17,0,1942,30.8%,31,w,4495.59,4495.59,7824.370000,7824.37,5504.41,2319.96,0.0,0.00,0.0000,Aug-2020,356.08,Sep-2020,Aug-2020,0,...,22,2,9,1,17,0.0,0,0,1,74.2,0.0,0,0,73669,59194,4000,67369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#That fixed the 2 NaN's that were in every row.

df.shape
df.isnull().sum().sort_values()

inq_fi                                             0
mo_sin_old_rev_tl_op                               0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
total_cu_tl                                        0
total_rev_hi_lim                                   0
open_rv_24m                                        0
open_rv_12m                                        0
total_bal_il                                       0
open_il_24m                                        0
open_il_12m                                        0
open_act_il                                        0
open_acc_6m                                        0
tot_cur_bal                                        0
tot_coll_amt                                       0
acc_now_delinq                                     0
application_type                                   0
policy_code                                        0
mo_sin_rcnt_rev_tl_op                              0
collections_12_mths_ex_med                         0
mo_sin_rcnt_tl                                     0
num_accts_ever_120_pd                              0
total_il_high_credit_limit                         0
total_bc_limit                                     0
total_bal_ex_mort                                  0
tot_hi_cred_lim                                    0
tax_liens                                          0
pub_rec_bankruptcies                               0
pct_tl_nvr_dlq                                     0
num_tl_op_past_12m                                 0
num_tl_90g_dpd_24m                                 0
num_tl_30dpd                                       0
num_sats                                           0
num_rev_tl_bal_gt_0                                0
num_rev_accts                                      0
num_op_rev_tl                                      0
num_il_tl                                          0
num_bc_tl                                          0
num_bc_sats                                        0
num_actv_rev_tl                                    0
num_actv_bc_tl                                     0
mort_acc                                           0
last_pymnt_amnt                                    0
max_bal_bc                                         0
collection_recovery_fee                            0
earliest_cr_line                                   0
delinq_2yrs                                        0
addr_state                                         0
zip_code                                           0
title                                              0
purpose                                            0
pymnt_plan                                         0
loan_status                                        0
issue_d                                            0
inq_last_6mths                                     0
verification_status                                0
home_ownership                                     0
sub_grade                                          0
grade                                              0
installment                                        0
int_rate                                           0
term                                               0
funded_amnt_inv                                    0
funded_amnt                                        0
loan_amnt                                          0
annual_inc                                         0
open_acc                                           0
debt_settlement_flag                               0
total_rec_int                                      0
total_rec_prncp                                    0
total_pymnt_inv                                    0
total_pymnt                                        0
pub_rec                                            0
out_prncp_inv                                      0
out_prncp                                          0
initial_list_status                                0
revol_bal                                          0
total_rec_late_fee                                 0
recoveries                                         0
total_acc                                          0
last_credit_pull_d                                 1
avg_cur_bal                                       13
all_util                                          37
revol_util                                       156
last_pymnt_d                                     159
dti                                              237
mths_since_recent_bc                            1591
bc_open_to_buy                                  1691
percent_bc_gt_75                                1692
bc_util                                         1754
num_tl_120dpd_2m                                2859
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
hardship_flag                                   4786
emp_length                                     11704
mths_since_recent_inq                          16047
il_util                                        20274
emp_title                                      20947
next_pymnt_d                                   46258
mths_since_last_delinq                         72196
mths_since_recent_revol_delinq                 91630
mths_since_last_major_derog                    99232
mths_since_recent_bc_dlq                      103243
hardship_amount                               110489
hardship_payoff_balance_amount                110489
hardship_last_payment_amount                  110489
orig_projected_additional_accrued_interest    110499
annual_inc_joint                              111630
sec_app_collections_12_mths_ex_med            111630
sec_app_chargeoff_within_12_mths              111630
sec_app_num_rev_accts                         111630
sec_app_open_act_il                           111630
sec_app_open_acc                              111630
dti_joint                                     111630
sec_app_inq_last_6mths                        111630
sec_app_earliest_cr_line                      111630
revol_bal_joint                               111630
sec_app_mort_acc                              111630
sec_app_revol_util                            111888
mths_since_last_record                        112962
verification_status_joint                     113564
hardship_length                               115276
hardship_end_date                             115276
hardship_start_date                           115276
hardship_status                               115276
deferral_term                                 115276
hardship_reason                               115277
hardship_dpd                                  115277
payment_plan_start_date                       115289
hardship_type                                 115290
hardship_loan_status                          117394
sec_app_mths_since_last_major_derog           123258
debt_settlement_flag_date                     127475
settlement_status                             127475
settlement_amount                             127475
settlement_date                               127475
settlement_term                               127475
settlement_percentage                         127475
desc                                          128412
url                                           128412
member_id                                     128412
id                                            128412
dtype: int64

In [ ]:
#Drop all the columns that are 100% null values

df = df.drop(['id','member_id','url','desc'], axis=1)

KeyError: ignored

In [ ]:
#Check the columns have been deleted

df.shape

(128412, 140)

In [ ]:
#Look at the first 10 values on the interest rate

df['int_rate'].head(10)

0     14.47%
1     12.98%
2     13.56%
3     13.56%
4     10.72%
5     20.89%
6     26.31%
7     23.40%
8     19.92%
9     17.97%
Name: int_rate, dtype: object

In [ ]:
#Look at a specific value on the int_rate column

df['int_rate'][5]

' 20.89%'

In [ ]:
#Check what type of value it is

type(df['int_rate'][5])

str

In [ ]:
#Convert the string into a number by: 
#getting rid of the space before the value
#getting rid of the % sign

test = ' 33.33%'

In [ ]:
#This gets rid of the space

test.strip()

'33.33%'

In [ ]:
#This gets rid of the %

test.strip('%')

' 33.33'

In [ ]:
#This gets rid of both at the same time
#Checking what type the value is now.
#Still a string.

type(test.strip().strip('%'))

str

In [ ]:
#Casting the string to make it into a float

float('33.33')

33.33

In [ ]:
#Adding float to the strip action

type(float(test.strip().strip('%')))

float

In [ ]:
#Create a function to convert the int_rate to floats
import numpy as np
def int_rate_to_float(cell_contents):
  return float(cell_contents.strip().strip("%"))

In [ ]:
#Testing the function

type(int_rate_to_float(test))

float

In [ ]:
#Create a for loop to apply the function to the list

new_list = []

for cell in df['int_rate']:
  new_list.append(int_rate_to_float(cell))

type(new_list[0:15])

list

In [ ]:
#convert the list into a series
df['new_int_rate'] = pd.Series(new_list)

df['new_int_rate'].head()

0    14.47
1    12.98
2    13.56
3    13.56
4    10.72
Name: new_int_rate, dtype: float64

In [ ]:
#Look at datatypes in the last 5 columns

df.dtypes[-5:]

settlement_date           object
settlement_amount        float64
settlement_percentage    float64
settlement_term          float64
new_int_rate             float64
dtype: object

In [ ]:
#Calculate mean of new int_rate column

df['new_int_rate'].mean()

12.928038734699749

In [ ]:
#Do this again using the apply function

df['int_rate_float_apply'] = df['int_rate'].apply(int_rate_to_float)

df['int_rate_float_apply'].head(10)
df.dtypes[-5:]
df['int_rate_float_apply'].mean()

12.928038734699749

In [ ]:
#Look at the employment title column
df['emp_title'].value_counts()[:20]

Teacher                     2090
Manager                     1773
Registered Nurse             952
Driver                       924
RN                           726
Supervisor                   697
Sales                        580
Project Manager              526
General Manager              523
Office Manager               521
Owner                        420
Director                     402
Operations Manager           387
Truck Driver                 387
Nurse                        326
Engineer                     325
Sales Manager                304
manager                      301
Supervisor                   270
Administrative Assistant     269
Name: emp_title, dtype: int64

In [ ]:
#How many unique titles are there
#almost 44k

len(df['emp_title'].value_counts())
len(df['emp_title'].unique())

#How many null counts are there?

df['emp_title'].isnull().sum()

20947

In [ ]:
#Clean up the emp_title values

def clean_title(job_title):
  if isinstance(job_title, str):
    return job_title.title().strip()
  else:
    return "Unknown"

In [ ]:
#Clean these examples

examples = ['owner', 'Supervisor', ' Project Manager', np.NaN]

for title in examples:
  print(clean_title(title))

Owner
Supervisor
Project Manager
Unknown

In [ ]:
#written in a list comprehension

[clean_title(title) for title in examples]

['Owner', 'Supervisor', 'Project Manager', 'Unknown']

In [ ]:
df['clean_emp_title'] = df['emp_title'].apply(clean_title)

df['clean_emp_title'].head(50)

0                                    Conductor
1                                      Printer
2                              Project Manager
3                                         Lmsw
4                              Program Manager
5                                Gas Attendant
6             Financial Relationship Associate
7                          Sale Representative
8                             Material Handler
9                               Administrative
10                                    Security
11                          Nursing Supervisor
12                                     Unknown
13                   Instructional Coordinator
14                          Driver Coordinator
15    Assistant Athletic Director Of Marketing
16                                     Unknown
17                          Production Manager
18                                   Carpenter
19                                 Casino Host
20                                      Driver
21                            Business Analyst
22                                      Banker
23                            Shift Supervisor
24                   Program Support Assistant
25                                    Operator
26                                    Engineer
27        Assistant To The Treasurer (Payroll)
28                       Sales Account Manager
29                           Financial Advisor
30                    Reimbursement Specialist
31                                      Driver
32                                         Cna
33                                     Unknown
34                                 Haz Mat S/R
35            Sr. Vice President -Risk Manager
36                              Senior Manager
37                      Reference/Ya Librarian
38             Senior Director Risk Management
39                        Help Tech Supervisor
40                          Machinst/Programer
41                                     Unknown
42                                     Unknown
43                                  Bus Driver
44                                     Manager
45                      Operations Coordinator
46                              Bakery Manager
47                                    Shipping
48                               Especialist 1
49                                     Teacher
Name: clean_emp_title, dtype: object

In [ ]:
df['clean_emp_title'].value_counts(ascending=False)[:20]

Unknown               20947
Teacher                2557
Manager                2395
Registered Nurse       1418
Driver                 1258
Supervisor             1160
Truck Driver            920
Rn                      834
Office Manager          805
Sales                   803
General Manager         791
Project Manager         720
Owner                   625
Director                523
Operations Manager      518
Sales Manager           500
Police Officer          440
Nurse                   425
Technician              420
Engineer                412
Name: clean_emp_title, dtype: int64

In [ ]:
df['clean_emp_title'].isnull().sum()

0

In [ ]:
#Find columns for date and time

[col for col in df if col.endswith('_d')]

['issue_d', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d']

In [ ]:
#look at issue_d

df['issue_d'][:20]

0     Dec-2018
1     Dec-2018
2     Dec-2018
3     Dec-2018
4     Dec-2018
5     Dec-2018
6     Dec-2018
7     Dec-2018
8     Dec-2018
9     Dec-2018
10    Dec-2018
11    Dec-2018
12    Dec-2018
13    Dec-2018
14    Dec-2018
15    Dec-2018
16    Dec-2018
17    Dec-2018
18    Dec-2018
19    Dec-2018
Name: issue_d, dtype: object

In [ ]:
#convert the column to a datetime format

df['issue_d'] = pd.to_datetime(df['issue_d'], infer_datetime_format=True)

df['issue_d'].head()
df.dtypes[:15]

loan_amnt                       int64
funded_amnt                     int64
funded_amnt_inv               float64
term                           object
int_rate                       object
installment                   float64
grade                          object
sub_grade                      object
emp_title                      object
emp_length                     object
home_ownership                 object
annual_inc                    float64
verification_status            object
issue_d                datetime64[ns]
loan_status                    object
dtype: object

In [ ]:
df['issue_d'].iloc[0]
df['issue_d'].head().values
df['issue_d'].dt.year

0         2018
1         2018
2         2018
3         2018
4         2018
          ...
128407    2018
128408    2018
128409    2018
128410    2018
128411    2018
Name: issue_d, Length: 128412, dtype: int64

In [ ]:
#add two new columns, the issue year and month

df['issue_year'] = df['issue_d'].dt.year
df['issue_month'] = df['issue_d'].dt.month

df.dtypes[-5:]
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,...,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,new_int_rate,int_rate_float_apply,clean_emp_title,issue_year,issue_month
0,27975,27975,27975.0,36 months,14.47%,962.52,C,C2,Conductor,10+ years,MORTGAGE,180000.0,Not Verified,2018-12-01,Fully Paid,n,credit_card,Credit card refinancing,117xx,NY,11.47,0,Jul-1995,0,39.0,NaN,10,0,29711,66.8%,19,w,0.00,0.00,31804.529849,31804.53,27975.00,3829.53,0.0,0.00,0.0000,Jan-2020,20288.02,NaN,Mar-2020,0,NaN,1,Individual,NaN,...,0.0,0,0,0,78.9,60.0,0,0,286525,45387,29500,25025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47,14.47,Conductor,2018,12
1,10000,10000,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7352.95,7352.95,4487.310000,4487.31,2647.05,1840.26,0.0,0.00,0.0000,Aug-2020,227.43,Sep-2020,Aug-2020,0,NaN,1,Individual,NaN,...,0.0,0,0,1,100.0,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,12.98,12.98,Printer,2018,12
2,28000,28000,28000.0,60 months,13.56%,645.15,C,C1,Project Manager,10+ years,MORTGAGE,128500.0,Source Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,760xx,TX,27.35,1,Jul-1987,0,24.0,NaN,16,0,55206,75%,31,w,20667.91,20667.91,12871.360000,12871.36,7332.09,5539.27,0.0,0.00,0.0000,Aug-2020,645.15,Sep-2020,Aug-2020,0,71.0,1,Individual,NaN,...,NaN,0,0,1,94.0,100.0,0,0,542027,128345,55000,60331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,13.56,13.56,Project Manager,2018,12
3,16000,16000,16000.0,60 months,13.56%,368.66,C,C1,LMSW,10+ years,RENT,46000.0,Not Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,787xx,TX,11.09,1,Oct-1997,1,11.0,NaN,9,0,18946,32.1%,21,w,11503.84,11503.84,7570.880000,7570.88,4496.16,3074.72,0.0,0.00,0.0000,Aug-2020,368.66,Sep-2020,Aug-2020,0,NaN,1,Individual,NaN,...,0.0,0,0,1,94.7,20.0,0,0,138125,128218,57600,79125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,13.56,13.56,Lmsw,2018,12
4,7500,7500,7500.0,36 months,10.72%,244.55,B,B2,Program Manager,2 years,RENT,84000.0,Not Verified,2018-12-01,Charged Off,n,debt_consolidation,Debt consolidation,600xx,IL,3.86,0,May-2005,1,NaN,114.0,9,1,2200,12.6%,17,w,0.00,0.00,2829.930000,2829.93,1465.61,484.09,0.0,880.23,158.4414,Sep-2019,244.55,NaN,Mar-2020,0,NaN,1,Individual,NaN,...,0.0,0,0,2,76.5,0.0,1,0,403892,20833,17400,16812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72,10.72,Program Manager,2018,12

In [ ]:
#Convert 'earliest_cr_line' to date time format

df['earliest_cr_line'].head()
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], infer_datetime_format=True)
df['earliest_cr_line'].head()

0   1995-07-01
1   2007-05-01
2   1987-07-01
3   1997-10-01
4   2005-05-01
Name: earliest_cr_line, dtype: datetime64[ns]

In [ ]:

df['issue_d'] - df['earliest_cr_line']

0         8554 days
1         4232 days
2        11476 days
3         7731 days
4         4962 days
            ...
128407   12114 days
128408   13241 days
128409    4505 days
128410    3652 days
128411    4413 days
Length: 128412, dtype: timedelta64[ns]

In [ ]:
#Make a column for the length of time that each row had a credit line
df['days_from_earliest_credit_to_issue'] = df['issue_d'] - df['earliest_cr_line']
df['days_from_earliest_credit_to_issue'].head()

0    8554 days
1    4232 days
2   11476 days
3    7731 days
4    4962 days
Name: days_from_earliest_credit_to_issue, dtype: timedelta64[ns]

In [ ]:
#Find the oldest credit line in the data set
df['days_from_earliest_credit_to_issue'].describe()

count                       128412
mean     5859 days 21:23:44.726635
std      2886 days 12:51:13.941888
min             1126 days 00:00:00
25%             4049 days 00:00:00
50%             5266 days 00:00:00
75%             7244 days 00:00:00
max            25171 days 00:00:00
Name: days_from_earliest_credit_to_issue, dtype: object

In [ ]:
#ASSIGNMENT: Convert the 'term' column from string to integer

df['term'][3]

#there's a space to strip, and " months" to strip

' 60 months'

In [ ]:
#setting up an example to test
term_test = ' 4 months'

#fixing one thing at a time
term_test.strip()
term_test.strip(' months')

#putting all the fixes together

term_test.strip().strip(' months')

'4'

In [ ]:
#Using the apply code

def term_fix(cell):
 return int(cell.strip().strip(' months'))

In [ ]:
df['term_clean'] = df['term'].apply(term_fix)

df.head()
df['term_clean'].describe()
df['term_clean'].head()

0    36
1    60
2    60
3    60
4    36
Name: term_clean, dtype: int64

In [ ]:
#ASSIGNMENT: Make a column named loan_status_is_great. 
#It should contain the integer 1 if loan_status is "Current" or "Fully Paid." 
#Else it should contain the integer 0.

#Here is the test
loan_test = ['Current']


def binary_loan_function(status):
  if status in ['Current','Fully Paid']:
    return 1
  else:
    return 0

for status in loan_test:
  print(binary_loan_function(status))

1

In [ ]:
#Here is the creation of the new column

df['loan_status_is_great'] = df['loan_status'].apply(binary_loan_function)

df.head()
df['loan_status_is_great'].value_counts()
df['loan_status_is_great'][-20:]

128392    1
128393    1
128394    1
128395    1
128396    1
128397    1
128398    1
128399    1
128400    1
128401    1
128402    1
128403    1
128404    1
128405    1
128406    1
128407    0
128408    1
128409    1
128410    1
128411    1
Name: loan_status_is_great, dtype: int64

In [ ]:
#Make last_pymnt_d_month and last_pymnt_d_year columns.

df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], infer_datetime_format=True)
df['last_pymnt_d'].head()

df['lastpymnt_d_month'] = df['last_pymnt_d'].dt.month.astype('Int64')
df['lastpymnt_d_month'].head()

df['lastpymnt_d_year'] = df['last_pymnt_d'].dt.year.astype('Int64')

df['lastpymnt_d_year'].head()

NameError: ignored

In [ ]:
#I figured out that my columns for last payment month and year were floats because there were NaN's in the columns.
#The fix I used was to add ".astype('Int64')" to the function.

df['lastpymnt_d_month'].isnull().sum()

159

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [2]:
#One other column has a % in it: revol_util. Remove and convert to floats. There are NaN's
import pandas as pd
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-09-07 01:18:06--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 54.148.13.215, 54.244.115.45, 35.161.89.82
Connecting to resources.lendingclub.com (resources.lendingclub.com)|54.148.13.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [               <=>  ]  22.28M  6.64MB/s    in 4.0s

2020-09-07 01:18:11 (5.53 MB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [23360898]

In [3]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [11]:
df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1, skipfooter=2, engine='python')

df.head()
df.tail()

        id  member_id  ...  settlement_percentage  settlement_term
128407 NaN        NaN  ...                    NaN              NaN
128408 NaN        NaN  ...                    NaN              NaN
128409 NaN        NaN  ...                    NaN              NaN
128410 NaN        NaN  ...                    NaN              NaN
128411 NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [14]:
#check what type of value revol_util is.
type(df['revol_util'][3])
#It's a string

str

In [20]:
#First I'll do a test to see if it will work on one input

test = '5.5%'

test_clean = float(test.strip('%'))

type(test_clean)

#df['revol_util_clean'] = float(df['revol_util'].strip('%'))

float

In [30]:
#My conditions aren't working, I guess it's because of the NaN's. There are 159 of them.

df['revol_util'].isnull().sum()

156

In [47]:
#I'll try using an if statement

pd.set_option('display.max_rows', 200)

def clean_util(util_value):
  if isinstance(util_value, str):
    return float(util_value.strip('%'))
  else:
    return util_value

df['revol_util_clean'] = df['revol_util'].apply(clean_util)
df['revol_util_clean'][100:200]
df['revol_util_clean'].isnull().sum()

#It worked! And the null values remain unchanged.

156

In [52]:
#Modify the emp_title so it returns "Other" if the title is not in the top 20.

df['emp_title'].value_counts()[:20]

Teacher                     2090
Manager                     1773
Registered Nurse             952
Driver                       924
RN                           726
Supervisor                   697
Sales                        580
Project Manager              526
General Manager              523
Office Manager               521
Owner                        420
Director                     402
Truck Driver                 387
Operations Manager           387
Nurse                        326
Engineer                     325
Sales Manager                304
manager                      301
Supervisor                   270
Administrative Assistant     269
Name: emp_title, dtype: int64

In [88]:
#I made a list
#created a def function using an if/else statement
#created a new column and used .apply

mylist = ['Teacher','Manager','Registered Nurse','Driver','RN','Supervisor','Sales','Project Manager','General Manager','Office Manager','Owner','Director','Truck Driver','Operations Manager','Nurse','Engineer','Sales Manager','manager','Supervisor','Administrative Assistant',]

def top_twenty(x):
  if x in mylist:
    return x
  else:
    return 'Other'

df['new_emp_title'] = df['emp_title'].apply(top_twenty)
df['new_emp_title'][:100]

0               Other
1               Other
2     Project Manager
3               Other
4               Other
5               Other
6               Other
7               Other
8               Other
9               Other
10              Other
11              Other
12              Other
13              Other
14              Other
15              Other
16              Other
17              Other
18              Other
19              Other
20             Driver
21              Other
22              Other
23              Other
24              Other
25              Other
26           Engineer
27              Other
28              Other
29              Other
30              Other
31              Other
32              Other
33              Other
34              Other
35              Other
36              Other
37              Other
38              Other
39              Other
40              Other
41              Other
42              Other
43              Other
44            Manager
45              Other
46              Other
47              Other
48              Other
49            Teacher
50              Other
51              Other
52              Other
53              Other
54              Other
55              Other
56              Other
57              Other
58              Other
59              Other
60              Other
61              Other
62              Other
63              Other
64              Other
65              Other
66              Other
67              Other
68              Other
69              Other
70              Other
71              Other
72              Other
73            Teacher
74              Other
75              Other
76              Other
77              Other
78           Director
79    General Manager
80              Other
81              Other
82            Manager
83              Other
84              Other
85              Other
86              Other
87              Other
88              Other
89              Other
90              Sales
91              Other
92            Teacher
93              Other
94              Other
95              Other
96              Other
97              Other
98              Other
99              Other
Name: new_emp_title, dtype: object

In [89]:
#Check if the list of new_emp_title has 21 unique values

df['new_emp_title'].value_counts()

Other                       115979
Teacher                       2090
Manager                       1773
Registered Nurse               952
Driver                         924
RN                             726
Supervisor                     697
Sales                          580
Project Manager                526
General Manager                523
Office Manager                 521
Owner                          420
Director                       402
Truck Driver                   387
Operations Manager             387
Nurse                          326
Engineer                       325
Sales Manager                  304
manager                        301
Administrative Assistant       269
Name: new_emp_title, dtype: int64

In [ ]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [ ]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [ ]:
# %cd instacart_2017_05_01